---
# tasks file for docker-install
- name: Add key for docker repo
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Install docker repo
  copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list
    mode: 0644

- name: Install packges for docker
  apt:
    name: docker-ce
    state: installed
    update_cache: yes
