---
# tasks file for kube-master-install

#- name: Check if the kube cluster is already running
#  command: 'nc localhost 6443 -v -z'
#  ignore_errors: yes
#  register:  is_kube_running

- name: Start Kubernetes cluster
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16"

- name: Get Kube token
  raw: "kubeadm token list | grep -v TOKEN | awk \'{print $1}\'"
  register: token

- name: Debug
  debug:
    msg: '{{ token }}'


